### ISSUE TITLE
Submit to sublimehq/Packages?

### ISSUE THREAD

**Issue by mikemee** [gbaptista/sublime-3-fennel#13]
Any thoughts on submitting this as a package to https://github.com/sublimehq/Packages ?  Then it would become part of many standard distros (like https://github.com/sharkdp/bat ). 

I'm happy to give it a try, though it's likely better coming from someone maintaining this (great!) repo.  Otoh, it's "yet another thing to do" when this repo is updated.

**Comment by mikemee** [comment]
Hmm, it seems they don't want new packages at this stage, per:

https://github.com/sublimehq/Packages#new-packages

Hmm, maybe it should be an addition to the existing Lisp package, or Lua?  

I'm fast getting out of my depth here - I know very little about sublime.

**Comment by mikemee** [comment]
After further research, it seems that 168 installs via https://packagecontrol.io/packages/Fennel is unlikely to prompt its inclusion in the standard packages.

Closing this issue. Apologies for the noise!

**Comment by gbaptista** [comment]
Got it. Thanks for reaching out and for the research, @mikemee!
