### ISSUE TITLE
Issues with Comments-Aware Enter

### ISSUE THREAD

**Issue by turbo** [gbaptista/sublime-3-fennel#5]
First off, thanks for making first-class support for Fennel possible in Sublime!

I have a very minor issue. I use another package, [Comments-Aware Enter](https://github.com/Suor/CommentsAwareEnter) to improve the editing experience with comments (auto-indentation, split & join comments, etc.). It works with all languages (even weird ones like MoonScript, but also standard Lua), but it seems to fail with this Fennel package. All its smart features don't function. 

Now, I don't know if the root cause for this is with the Fennel package or the comments one, but I'm also not knowledgeable enough about Sublime packages to debug this.

**Comment by gbaptista** [comment]
Thanks for reporting and submitting the fix!
